
[project]
name = "UCF_Search_Service_Django"
version = "2.6.6"
dependencies = [
    "beautifulsoup4",
    "boto3",
    "Django==3.2.*",
    "django-cors-headers",
    "djangorestframework",
    "django-filter",
    "django_mysql",
    "django-saml2-auth-ai",
    "django-widget-tweaks",
    "drf-dynamic-fields",
    "fuzzywuzzy",
    "gunicorn",
    "lxml==4.6.5",
    "mysqlclient",
    "Pillow==9.0.1",
    "progress",
    "python-dateutil",
    "pysaml2",
    "python-Levenshtein",
    "raven",
    "requests",
    "sqlparse",
    "tabulate",
    "Unidecode"
]

[project.optional-dependencies]
dev = [
    "django-extensions",
    "Werkzeug"
]
